"use client";

import { useState } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";

export function FAQ() {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  const faqs = [
    {
      q: "Are videos created by Vidmo eligible for YouTube Shorts and TikTok monetization?",
      a: "Yes, absolutely. Every video generated by Vidmo uses unique, original AI-authored scripts, copyright-cleared licensed stock footage/B-roll, and commercially licensed neural voice models. Thousands of our creators are actively monetized in the YouTube Partner Program and TikTok Creator Rewards Program.",
    },
    {
      q: "How does the Auto-Scheduler post to YouTube, TikTok, and Instagram without manual work?",
      a: "Vidmo integrates directly with official developer APIs (YouTube Data API v3, TikTok for Business Content API, and Meta Graph API). Once you authorize your accounts, Vidmo uploads and publishes directly into your channel at your scheduled peak hours without needing phone push notifications or manual approvals.",
    },
    {
      q: "How does the Email Video Newsletter feature work?",
      a: "For email campaigns, Vidmo automatically renders a high-frame-rate animated video preview (GIF) with an embedded play button and generates standard HTML embed code compatible with Klaviyo, Mailchimp, Substack, Beehiiv, and HubSpot. When subscribers click the video, they are taken directly to your video watch page or custom CTA landing page.",
    },
    {
      q: "Can I clone my own voice or customize the video styling?",
      a: "Yes! On our Pro Autopilot and Agency tiers, you can upload a 60-second voice sample to clone your exact voice and accent. You can also customize your caption fonts, colors, brand logos, B-roll preferences, and intro/outro transitions.",
    },
    {
      q: "Can I preview and approve videos before they are published?",
      a: "Yes. You have full control. You can run Vidmo in '100% Hands-Free Autopilot' mode (where videos render and post automatically on your calendar), or in 'Approval Queue' mode, where Vidmo drafts everything and notifies you to approve with a single click before posting.",
    },
    {
      q: "Can I cancel my subscription at any time?",
      a: "Yes. There are no contracts or commitments. You can cancel your subscription with 1 click directly inside your account settings at any time, and you will continue to have full access until the end of your billing cycle.",
    },
  ];

  return (
    <section id="faq" className="relative py-24 bg-zinc-950 border-t border-white/10 overflow-hidden">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-xs font-semibold text-cyan-300 mb-4">
            <HelpCircle className="w-3.5 h-3.5" />
            <span>Got Questions? We&apos;ve Got Answers</span>
          </div>
          <h2 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight">
            Frequently Asked <span className="text-gradient-cyan">Questions</span>
          </h2>
          <p className="mt-4 text-base sm:text-lg text-zinc-400">
            Everything you need to know about Vidmo AI video generation and auto-scheduling.
          </p>
        </div>

        {/* Accordion List */}
        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openIdx === index;

            return (
              <div
                key={index}
                className={`rounded-2xl transition-all duration-200 border ${
                  isOpen
                    ? "bg-zinc-900/80 border-violet-500/40 shadow-lg shadow-violet-500/10"
                    : "bg-zinc-900/40 border-white/10 hover:border-white/20"
                }`}
              >
                <button
                  onClick={() => setOpenIdx(isOpen ? null : index)}
                  className="w-full text-left p-5 sm:p-6 flex items-center justify-between gap-4"
                >
                  <span className="text-base sm:text-lg font-bold text-white leading-snug">
                    {faq.q}
                  </span>
                  <div
                    className={`p-1.5 rounded-full bg-white/5 shrink-0 transition-transform duration-300 ${
                      isOpen ? "rotate-180 bg-violet-500/20 text-violet-400" : "text-zinc-400"
                    }`}
                  >
                    <ChevronDown className="w-5 h-5" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-5 sm:px-6 pb-6 pt-1 text-sm sm:text-base text-zinc-300 leading-relaxed border-t border-white/5">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Need more help */}
        <div className="mt-12 text-center p-6 rounded-2xl bg-zinc-900/40 border border-white/10">
          <p className="text-sm text-zinc-300">
            Have a question not listed here? Our video automation experts are ready to help.
          </p>
          <a
            href="#footer"
            className="mt-2 inline-block text-xs sm:text-sm font-bold text-violet-400 hover:text-violet-300"
          >
            Chat with our 24/7 Support Team &rarr;
          </a>
        </div>
      </div>
    </section>
  );
}
